### PR TITLE
Update FG and Gradle

### PR DESCRIPTION
**Pull request by KatatsumuriPan**
Using [anatawa12's ForgeGradle-2.3 fork](https://github.com/anatawa12/ForgeGradle-2.3) and update Gradle to 6.

### CODE REVIEW

**Comment by brachy84** [comment]
where rfg

**Comment by Rongmario** [comment]
If possible, updating to use [RetroFuturaGradle](https://github.com/GTNewHorizons/RetroFuturaGradle) would be better, [template](https://github.com/CleanroomMC/TemplateDevEnv) here if you need any guidance!

**Comment by tier940** [comment]
I was thinking with Mr. KatatsumuriPan while VC on Discord, but gave up because of the api and api2 folders.

**Comment by KatatsumuriPan** [comment]
Can I use [GTCEu's Buildscripts](https://github.com/GregTechCEu/Buildscripts) without any problems about apis?

**Comment by Rongmario** [comment]
If you're comfortable with it, go ahead!

**Comment by KatatsumuriPan** [comment]
I created PR https://github.com/CleanroomMC/BetterQuesting/pull/90

**Comment by Rongmario** [comment]
#90 now supersedes this. Closing.

**Pull request closed without merging**
